language: c
sudo: false

env:
  global:
  - PRETTYNAME="Hygrometer Sensor (Rain Drop and Soil Moisture)"

before_install:
- source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)

script:
- build_main_platforms
